---
services:
  typst:
    image: ghcr.io/typst/typst:latest
    container_name: typst_compiler
    volumes:
      - .:/workspace
    working_dir: /workspace
  vale:
    image: docker.io/grafana/vale:latest
    container_name: vale
    command: ["vale", "sync"]
    volumes:
      - .:/workspace
    working_dir: /workspace
