---
name: "build"

on: ["push"]

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "xu-cheng/latex-action@v3"
        with:
          root_file: "main.tex"
      - name: Rename output file with current date
        run: mv "main.pdf" "easterson_kirk_cv_$(date +'%Y_%m_%d').pdf"
      - uses: "actions/upload-artifact@v4"
        with:
          path: "main.pdf"
