---
name: "build"

on: ["push"]

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "xu-cheng/latex-action@v3"
        with:
          root_file: "main.tex"
      - name: "Get current date"
        run: echo "OUT=$(date +'easterson_kirk_cv_%Y_%m_%d')" >> $GITHUB_ENV
      - name: Rename output file
        run: mv "main.pdf" "${{env.OUT}}.pdf"
      - uses: "actions/upload-artifact@v4"
        with:
          path: "${{env.OUT}}.pdf"
