---
name: "build"

on: ["push"]

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "xu-cheng/latex-action@v3"
        with:
          working_directory: "./src/"
          root_file: "main.tex"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "artifact"
          path: "./src/main.pdf"

  release:
    needs: "build"
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Download artifact"
        id: "download-artifact"
        uses: "actions/download-artifact@v4"
        with:
          name: "artifact"
          path: "./"

      - name: "Get current date"
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: "Get short SHA"
        run: echo "SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: "Set release version"
        run: echo "version=${{env.TODAY}}_${{env.SHA_SHORT}}" >> "$GITHUB_OUTPUT"
        id: "version"

      - name: "Create release"
        uses: "actions/create-release@v1"
        id: "create_release"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          draft: false
          prerelease: false
          release_name: "${{steps.version.outputs.version}}"
          tag_name: "${{env.SHA_SHORT}}"

      - name: "Upload artifacts to release"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: "./main.pdf"
          asset_name: "easterson_kirk_cv_${{env.TODAY}}.pdf"
          asset_content_type: "application/pdf"
