---
name: "build"

on: ["push"]

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "xu-cheng/latex-action@v3"
        with:
          root_file: "main.tex"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y_%m_%d')"
      - uses: "actions/upload-artifact@v4"
        with:
          name: "easterson_kirk_cv_${{steps.date.outputs.date}}.pdf"
          path: "main.pdf"
